[package]
name = "npb_rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ep"
path = "src/ep.rs"

[[bin]]
name = "cg"
path = "src/cg.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scoped-pool = "1.0.0"
itertools = "0.10.5"