[package]
name = "npb_rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ep"
path = "src/ep.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
